# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'deneme.ui'
#
# Created by: PyQt5 UI code generator 5.15.7
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(800, 600)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.button1 = QtWidgets.QPushButton(self.centralwidget)
        self.button1.setGeometry(QtCore.QRect(260, 370, 251, 121))
        self.button1.setObjectName("button1")
        self.snake1 = QtWidgets.QLabel(self.centralwidget)
        self.snake1.setGeometry(QtCore.QRect(310, 100, 191, 20))
        self.snake1.setObjectName("snake1")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 800, 26))
        self.menubar.setObjectName("menubar")
        self.menuhaha1 = QtWidgets.QMenu(self.menubar)
        self.menuhaha1.setObjectName("menuhaha1")
        self.menuhaha2 = QtWidgets.QMenu(self.menubar)
        self.menuhaha2.setObjectName("menuhaha2")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.actionsicis1 = QtWidgets.QAction(MainWindow)
        self.actionsicis1.setObjectName("actionsicis1")
        self.menuhaha1.addAction(self.actionsicis1)
        self.menubar.addAction(self.menuhaha1.menuAction())
        self.menubar.addAction(self.menuhaha2.menuAction())

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.button1.setText(_translate("MainWindow", "PushButton"))
        self.snake1.setText(_translate("MainWindow", "snake serdar"))
        self.menuhaha1.setTitle(_translate("MainWindow", "haha1"))
        self.menuhaha2.setTitle(_translate("MainWindow", "haha2"))
        self.actionsicis1.setText(_translate("MainWindow", "sicis1"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
