# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'qtt.ui'
#
# Created by: PyQt5 UI code generator 5.15.7
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(652, 471)
        self.buttonleft = QtWidgets.QPushButton(Form)
        self.buttonleft.setGeometry(QtCore.QRect(130, 330, 93, 28))
        self.buttonleft.setObjectName("buttonleft")
        self.buttonright = QtWidgets.QPushButton(Form)
        self.buttonright.setGeometry(QtCore.QRect(400, 330, 93, 28))
        self.buttonright.setObjectName("buttonright")
        self.label1 = QtWidgets.QLabel(Form)
        self.label1.setGeometry(QtCore.QRect(150, 190, 341, 51))
        font = QtGui.QFont()
        font.setPointSize(16)
        self.label1.setFont(font)
        self.label1.setObjectName("label1")

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        self.buttonleft.setText(_translate("Form", "buttonleft"))
        self.buttonright.setText(_translate("Form", "buttonright"))
        self.label1.setText(_translate("Form", "Nothing to see here"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Form = QtWidgets.QWidget()
    ui = Ui_Form()
    ui.setupUi(Form)
    Form.show()
    sys.exit(app.exec_())
